"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./_context/AuthContext";
import { GlobalContextProvider } from "./_context/GlobalContext";
import { NextUIProvider } from "@nextui-org/system";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <GlobalContextProvider>
            <NextUIProvider>
              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={true}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                style={{ position: "absolute", top: 0, right: 0, zIndex: 9999 }}
              />
              <main className="dark text-foreground bg-background">
                {children}
              </main>
            </NextUIProvider>
          </GlobalContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
